# Generated by Django 3.0.4 on 2020-03-15 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200315_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='tasklist_name',
            new_name='task_list_name',
        ),
    ]
